package Modelo;
// Generated 02/12/2017 15:20:35 by Hibernate Tools 4.3.1



/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private int idProducto;
     private String nomProducto;
     private Integer cantProducto;
     private Double precio;

    public Producto() {
    }

	
    public Producto(int idProducto) {
        this.idProducto = idProducto;
    }
    public Producto(int idProducto, String nomProducto, Integer cantProducto, Double precio) {
       this.idProducto = idProducto;
       this.nomProducto = nomProducto;
       this.cantProducto = cantProducto;
       this.precio = precio;
    }
   
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }
    public String getNomProducto() {
        return this.nomProducto;
    }
    
    public void setNomProducto(String nomProducto) {
        this.nomProducto = nomProducto;
    }
    public Integer getCantProducto() {
        return this.cantProducto;
    }
    
    public void setCantProducto(Integer cantProducto) {
        this.cantProducto = cantProducto;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }

    @Override
    public String toString() {
        return "Producto{" + "idProducto=" + idProducto + ", nomProducto=" + nomProducto + ", cantProducto=" + cantProducto + ", precio=" + precio + '}';
    }




}


