/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package productoyprecio;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author capacitacion
 */
public class pantalla extends javax.swing.JFrame {
    ArrayList <productos> miLista = new ArrayList<>();
     ArrayList <String> presentacionLeche = new ArrayList<>();
     ArrayList <String> presentacionGalles = new ArrayList<>();
     GeneradorImpresion gestor;
     int posicion;
     String [] [] matrizDetalle;
     

    /**
     * Creates new form pantalla
     */
    public pantalla() {
        initComponents();
    }
    private ArrayList<productos> lista_productos=new ArrayList<productos>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        resultado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cargarlista = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaDetalle = new javax.swing.JTable();
        confirmar_btn = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Producto", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla1);

        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });

        jLabel1.setText("Resultado");

        cargarlista.setText("Cargar Lista");
        cargarlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarlistaActionPerformed(evt);
            }
        });

        tablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Presentacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaDetalle);

        confirmar_btn.setText("Confirmar");
        confirmar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmar_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cargarlista)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(confirmar_btn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cargarlista))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confirmar_btn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoActionPerformed

    private void cargarlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarlistaActionPerformed
        // TODO add your handling code here:
       String leche1="Entera";
       String leche2="Descremada";
       String leche3="Deslactosada";
       presentacionLeche.add(leche1);
       presentacionLeche.add (leche2);
       presentacionLeche.add (leche3);
       String galles1="Chips de Chocolate";
       String galles2="Vainilla";
       String galles3="Dulce de Leche";
       presentacionGalles.add(galles1);
       presentacionGalles.add(galles2);
       presentacionGalles.add(galles3);
       productos p1=new productos ("Leche", 20.0f, presentacionLeche);
       productos p2=new productos ("Galletitas", 30.0f, presentacionGalles);
       miLista.add(p1);
       miLista.add(p2);
       
       
        Object [][] matriz= new Object [miLista.size()][2];
        Object [] col=new Object []{"Producto","Precio"};
        int acumulador=0;
        for(int i=0;i<miLista.size();i++){
            matriz[i][0]=miLista.get(i).getProducto();
            matriz[i][1]=miLista.get(i).getPrecio();
            acumulador+=miLista.get(i).getPrecio();
            
        }
        
        tabla1.setAlignmentY(CENTER_ALIGNMENT);
        resultado.setText(String.valueOf(acumulador));
        this.cargarlista.setEnabled(false);
        tabla1.setModel(new javax.swing.table.DefaultTableModel(matriz, col));
        
    }//GEN-LAST:event_cargarlistaActionPerformed

    private void tabla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla1MouseClicked

        // TODO add your handling code here:
        posicion = tabla1.getSelectedRow();
        matrizDetalle=new String [miLista.get(posicion).getPresentacion().size()][1];
        String [] nomColDetalle=new String [] {"Presentacion"};
        for (int j=0;j<miLista.get(posicion).getPresentacion().size();j++){
            matrizDetalle[j][0]=miLista.get (posicion).getPresentacion().get(j);
         }
        tablaDetalle.setModel(new javax.swing.table.DefaultTableModel(matrizDetalle,nomColDetalle));
        
        
    }//GEN-LAST:event_tabla1MouseClicked

    private void confirmar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmar_btnActionPerformed
        if (cargarlista.isEnabled()==false){
        int decision=JOptionPane.showConfirmDialog(null,"¿Desea generar el informe?","Confirmacion", JOptionPane.YES_NO_OPTION);
            
           
            if(decision==JOptionPane.YES_OPTION){
                String numeroInforme =JOptionPane.showInputDialog("Numero de informe: ");
                int numero=Integer.parseInt(numeroInforme);
                if (numero>0){
                    gestor=new GeneradorImpresion(matrizDetalle, numero);
                    gestor.crearPantallaImpresion();
            
                }else{
                    System.out.println("NO VALIDO");
                }    
                
            }else if(decision==JOptionPane.NO_OPTION){
                   System.out.println("NO");
            }else{
                System.out.println ("Cancelar");
            }         
            
        }else{
            JOptionPane.showMessageDialog(null, "No hay datos cargados");
     
        }   
    }//GEN-LAST:event_confirmar_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargarlista;
    private javax.swing.JButton confirmar_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField resultado;
    private javax.swing.JTable tabla1;
    private javax.swing.JTable tablaDetalle;
    // End of variables declaration//GEN-END:variables
}
