/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzeria;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author 111mil
 */
public class TablaPedidos extends javax.swing.JFrame {
            private ArrayList <Pedido> pedidos = new ArrayList <> ();
            ArrayList<DetallePedido> detsPedidos1=new ArrayList<>();
            ArrayList<DetallePedido> detsPedidos2=new ArrayList<>();
            GeneradorImpresion gestor;
            int posicion;
            Object [][] matrizDetalle; 
            String cliente;
            String resultadof;
            
    /**
     * Creates new form TablaPedidos
     */
    public TablaPedidos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PantallaPedidos = new javax.swing.JTable();
        CargarPedidos_boton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        detallepizza = new javax.swing.JTable();
        D1 = new javax.swing.JLabel();
        resultado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        detalles_pedido = new javax.swing.JLabel();
        generarfactura = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccione un pedido:");

        PantallaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Número", "Fecha", "Hora", "Cliente"
            }
        ));
        PantallaPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PantallaPedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PantallaPedidos);

        CargarPedidos_boton.setText("Cargar Pedidos");
        CargarPedidos_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarPedidos_botonActionPerformed(evt);
            }
        });

        detallepizza.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Cantidad", "Pizza", "Tipo", "Variedad", "Tamaño", "Precio", "Subtotal"
            }
        ));
        jScrollPane3.setViewportView(detallepizza);

        D1.setText("Datos del Pedido Seleccionado:");

        detalles_pedido.setText("Detalles Pedido");

        generarfactura.setText("Generar factura");
        generarfactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarfacturaActionPerformed(evt);
            }
        });

        jLabel2.setText("Total");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CargarPedidos_boton))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(detalles_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(D1)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(generarfactura)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CargarPedidos_boton)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addComponent(D1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(detalles_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generarfactura)
                    .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargarPedidos_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarPedidos_botonActionPerformed
        // TODO add your handling code here:

        TipoPizza TPizza = new TipoPizza ("A la Parrilla","crocante y alta");
        TipoPizza TPizza2 = new TipoPizza ("Al Molde", "Angosta y más pequeña");
        TipoPizza TPizza3 = new TipoPizza ("A la Piedra", "Ancha y Crocante");

        TamañoPizza TamPizza = new TamañoPizza (8, "Chica");
        TamañoPizza TamPizza2 = new TamañoPizza (12,"Grande");

        VariedadPizza VPizza = new VariedadPizza ("Salsa de tomate, muzzarella, jamón y morrones", "Especial");
        VariedadPizza VPizza2 = new VariedadPizza ("Salsa de tomate, muzzarella, longaniza, aji molido", "Calabresa");
        VariedadPizza VPizza3 = new VariedadPizza ("Salsa de tomate, muzzarella, rodajas de tomate, orégano", " Napolitana");

        Pizza pizza1=new Pizza("Calabreza",120,TPizza,VPizza,TamPizza);
        Pizza pizza2=new Pizza("Palmitos",160,TPizza2,VPizza2,TamPizza2);

        EstadoPedido estPed1 = new EstadoPedido("Pendiente de Facturacion", "lalala");
        EstadoPedido estPed2 = new EstadoPedido ("Facturado", "Facturado");

        DetallePedido detPedido1= new DetallePedido(2, 200, estPed1, pizza1);
        DetallePedido detPedido2= new DetallePedido(1, 150, estPed2, pizza2);
        //Crear array de detalles y SETEAR ESA ARRAY

        Date fechCreaPedi1=new Date(117,9,6,18,30,0);
        Date fechCreaPedi2= new Date(117,10,13,19,26,0);
        Date fechEntregaPedi1=new Date(117,9,6,19,30,0);
        Date fechEntregaPedi2=new Date(117,10,13,20,30,0);
        detsPedidos1.add(detPedido1);
        detsPedidos1.add(detPedido2);
        detsPedidos2.add(detPedido2);

        Factura fact1 = new Factura (detsPedidos1);

        Pedido pedido1=new Pedido(fechCreaPedi1, fechEntregaPedi1, "Rolo", 1, fact1, estPed1, detsPedidos1);

        Factura fact2 = new Factura (detsPedidos2);

        Pedido pedido2= new Pedido(fechCreaPedi2,fechEntregaPedi2, "Cacho", 2, fact2, estPed2, detsPedidos2);

        pedidos.add(pedido1);
        pedidos.add(pedido2);

        Object [][] listadoPedido = new Object [pedidos.size()][4];

        String[] columnaPedido=new String[] {"Numero","Fecha","Hora","Cliente"};

        for(int i=0;i<pedidos.size();i++){

            listadoPedido[i][0] = pedidos.get(i).getNumero();
            listadoPedido[i][1] = pedidos.get(i).dameFecha();
            listadoPedido[i][2] = pedidos.get(i).dameHora();
            listadoPedido[i][3] = pedidos.get(i).getNombreCliente();

        }

        PantallaPedidos.setModel(new javax.swing.table.DefaultTableModel(listadoPedido,columnaPedido));
        this.CargarPedidos_boton.setEnabled(false);

    }//GEN-LAST:event_CargarPedidos_botonActionPerformed

    private void PantallaPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PantallaPedidosMouseClicked
        // TODO add your handling code here:
        int posicion=PantallaPedidos.getSelectedRow();
        //System.out.println(posicion);
        matrizDetalle= new Object [pedidos.get(posicion).getDetallesPedido().size()][7];
        //que tamaño tiene la matriz
        String [] col=new String []{"Cantidad","Pizza","Tipo","Variedad","Tamaño","Precio","Subtotal"};
        String numero=PantallaPedidos.getValueAt(posicion, 0).toString();
        String fechayhora=PantallaPedidos.getValueAt(posicion, 1).toString() + " " + PantallaPedidos.getValueAt(posicion, 2).toString();
        cliente=PantallaPedidos.getValueAt(posicion, 3).toString();
        detalles_pedido.setText("Número de Pedido: " + numero + "Fecha y Hora: " + fechayhora + "Cliente: " + cliente);
        //System.out.println(pedidos.get(posicion).getDetallesPedido().size());
        
        int acumulador=0;
        for (int i=0;i<pedidos.get(posicion).getDetallesPedido().size();i++){
           //System.out.println("Entre al for");
            
            matrizDetalle[i][0]=pedidos.get(posicion).getDetallesPedido().get(i).getCantidad();
            System.out.println(pedidos.get(posicion).getDetallesPedido().get(i).getCantidad());
            matrizDetalle[i][1]=pedidos.get(posicion).getDetallesPedido().get(i).getPizza().getNombre();
            matrizDetalle[i][2]=pedidos.get(posicion).getDetallesPedido().get(i).getPizza().getTipoPizza();
            matrizDetalle[i][3]=pedidos.get(posicion).getDetallesPedido().get(i).getPizza().getVariedad();
            matrizDetalle[i][4]=pedidos.get(posicion).getDetallesPedido().get(i).getPizza().getTamaño();
            matrizDetalle[i][5]=pedidos.get(posicion).getDetallesPedido().get(i).getPizza().getPrecio();
            matrizDetalle[i][6]=pedidos.get(posicion).getDetallesPedido().get(i).CalcTotalItem();
            
            acumulador+=pedidos.get(posicion).getDetallesPedido().get(i).CalcTotalItem();
            
                     

        }
        resultadof= Integer.toString(acumulador);
        resultado.setText(resultadof);
        
        
        detallepizza.setModel(new javax.swing.table.DefaultTableModel(matrizDetalle,col));
    }//GEN-LAST:event_PantallaPedidosMouseClicked

    private void generarfacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarfacturaActionPerformed
    if(CargarPedidos_boton.isEnabled()==false){
    int decision=JOptionPane.showConfirmDialog(null,"¿Desea generar la facura?","CONFIRMACIÓN",JOptionPane.YES_NO_OPTION);
    if(decision==JOptionPane.YES_NO_OPTION){
        String numerodefactura=JOptionPane.showInputDialog("Número de informe:");
        int numero=Integer.parseInt(numerodefactura);
        String fecha = PantallaPedidos.getValueAt(posicion, 1).toString();
        String hora = PantallaPedidos.getValueAt(posicion, 2).toString();
        
        if(numero>0){
            gestor=new GeneradorImpresion(matrizDetalle, numero, cliente, fecha, hora, resultadof);
            gestor.crearPantallaImpresion();
            
        }else{
            System.out.println("NO VALIDO");
        }
    }else if (decision==JOptionPane.NO_OPTION){
       System.out.println("NO"); 
    }else{
       System.out.println("Cancelar");   
    }
    }else{
            JOptionPane.showMessageDialog(null, "No hay datos cargados");      
    } 
   // TODO add your handling code here:
    }//GEN-LAST:event_generarfacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarPedidos_boton;
    private javax.swing.JLabel D1;
    private javax.swing.JTable PantallaPedidos;
    private javax.swing.JTable detallepizza;
    private javax.swing.JLabel detalles_pedido;
    private javax.swing.JButton generarfactura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField resultado;
    // End of variables declaration//GEN-END:variables
}
